import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import SideBar from "@/components/sidebar/SideBar";

export const metadata = {
    title: "eltabarak",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <SideBar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
